# Generated by Django 5.2.7 on 2025-10-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assignees_alter_worker_position'),
        ('tasks', '0002_alter_worker_position'),
    ]

    operations = [
    ]
